[project]
name = "mass-deportation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
    "tqdm>=4.67.1",
]
